# Generated by Django 3.2.3 on 2022-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineVersion',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('equest_number', models.CharField(blank=True, help_text='需求申请号', max_length=25, null=True, verbose_name='需求申请号')),
                ('demand_number', models.CharField(blank=True, help_text='需求编号', max_length=50, null=True, verbose_name='需求编号')),
                ('systemes', models.IntegerField(choices=[(0, '请选择'), (1, 'CRM'), (2, 'ESOP'), (3, '电渠'), (4, '账管'), (5, '终端'), (7, '知识库'), (8, '渠道APP'), (9, '酬金'), (10, '项目'), (11, '收入宝')], default=0, help_text='系统', verbose_name='系统')),
                ('requirements', models.CharField(help_text='业务需求', max_length=50, verbose_name='业务需求')),
                ('demand_type', models.IntegerField(choices=[(0, '请选择'), (1, '故障'), (2, '项目'), (3, '优化'), (4, '需求')], default=0, help_text='需求类型', verbose_name='需求类型')),
                ('demand_source', models.IntegerField(choices=[(0, '请选择'), (1, '互联网运营中心'), (2, '信息技术中心'), (3, '市场经营部')], default=0, help_text='需求来源', verbose_name='需求来源')),
                ('online_version', models.CharField(help_text='上线版本批次', max_length=50, verbose_name='上线版本批次')),
            ],
            options={
                'verbose_name': '上线表',
                'verbose_name_plural': '上线表',
                'db_table': 'dvadmin_online',
                'ordering': ('-online_version',),
            },
        ),
        migrations.CreateModel(
            name='OnlineVersionStatistics',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('online_version', models.CharField(help_text='上线版本批次', max_length=50, verbose_name='上线版本批次')),
                ('environment', models.CharField(help_text='环境', max_length=20, verbose_name='环境')),
                ('systems', models.CharField(help_text='系统', max_length=50, verbose_name='系统')),
                ('count', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('undeveloped', models.IntegerField(default=0, help_text='未开发完成', verbose_name='未开发完成')),
                ('unpublished', models.IntegerField(default=0, help_text='未发布', verbose_name='未发布')),
                ('not_configured', models.IntegerField(default=0, help_text='未配置', verbose_name='未配置')),
                ('demand_not_confirmed', models.IntegerField(default=0, help_text='需求未确认', verbose_name='需求未确认')),
                ('block', models.IntegerField(default=0, help_text='阻塞', verbose_name='阻塞')),
                ('joint_commissioning', models.IntegerField(default=0, help_text='联调中', verbose_name='联调中')),
                ('not_tested', models.IntegerField(default=0, help_text='未测试', verbose_name='未测试')),
                ('under_test', models.IntegerField(default=0, help_text='测试中', verbose_name='测试中')),
                ('test_pass', models.IntegerField(default=0, help_text='通过', verbose_name='通过')),
                ('test_fail', models.IntegerField(default=0, help_text='未通过', verbose_name='未通过')),
                ('fixed', models.IntegerField(default=0, help_text='已修复', verbose_name='已修复')),
                ('unable_to_test', models.IntegerField(default=0, help_text='通过（无法测试）', verbose_name='通过（无法测试）')),
                ('not_online_temporarily', models.IntegerField(default=0, help_text='暂不上线', verbose_name='暂不上线')),
                ('already_online', models.IntegerField(default=0, help_text='已经上线', verbose_name='已经上线')),
            ],
            options={
                'verbose_name': '上线需求统计表',
                'verbose_name_plural': '上线需求统计表',
                'db_table': 'dvadmin_online_version_statistics',
                'ordering': ('-online_version',),
            },
        ),
    ]
