# Generated by Django 3.2.3 on 2023-01-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('equest_number', models.CharField(blank=True, help_text='需求申请号', max_length=50, null=True, verbose_name='需求申请号')),
                ('demand_number', models.CharField(blank=True, help_text='需求编码', max_length=50, null=True, verbose_name='需求编码')),
                ('systems', models.CharField(blank=True, help_text='系统', max_length=20, null=True, verbose_name='系统')),
                ('requirements', models.CharField(blank=True, help_text='业务需求', max_length=255, null=True, verbose_name='业务需求')),
                ('demand_type', models.CharField(blank=True, help_text='需求类型', max_length=20, null=True, verbose_name='需求类型')),
                ('demand_source', models.CharField(blank=True, help_text='需求来源', max_length=20, null=True, verbose_name='需求来源')),
                ('bureau_manager', models.CharField(blank=True, help_text='局方负责人', max_length=10, null=True, verbose_name='局方负责人')),
                ('demand_complexity', models.CharField(blank=True, help_text='需求复杂度', max_length=5, null=True, verbose_name='需求复杂度')),
                ('demand_manager', models.CharField(blank=True, help_text='需求负责人', max_length=5, null=True, verbose_name='需求负责人')),
                ('development_manager', models.CharField(blank=True, help_text='开发负责人', max_length=20, null=True, verbose_name='开发负责人')),
                ('development_group_leader', models.CharField(blank=True, help_text='开发组长', max_length=5, null=True, verbose_name='开发组长')),
                ('tester', models.CharField(blank=True, help_text='测试负责人', max_length=5, null=True, verbose_name='测试负责人')),
                ('ost_development', models.CharField(blank=True, help_text='162部署情况', max_length=5, null=True, verbose_name='162部署情况')),
                ('ost_test_result', models.CharField(blank=True, help_text='162测试结果', max_length=10, null=True, verbose_name='162测试结果')),
                ('oft_development', models.CharField(blank=True, help_text='143部署情况', max_length=5, null=True, verbose_name='143部署情况')),
                ('oft_test_result', models.CharField(blank=True, help_text='143测试结果', max_length=10, null=True, verbose_name='143测试结果')),
                ('notes', models.CharField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('version_number', models.CharField(help_text='上线版本批次', max_length=10, verbose_name='上线版本批次')),
            ],
            options={
                'verbose_name': '上线表',
                'verbose_name_plural': '上线表',
                'db_table': 'dvadmin_online',
                'ordering': ('-id',),
            },
        ),
    ]
