# Generated by Django 3.2.3 on 2022-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_employee_certification_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, help_text='学历', max_length=5, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, help_text='等级', max_length=5, null=True, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduation_date',
            field=models.CharField(blank=True, help_text='毕业时间', max_length=10, null=True, verbose_name='毕业时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialized',
            field=models.CharField(blank=True, help_text='专业', max_length=20, null=True, verbose_name='专业'),
        ),
    ]
