# Generated by Django 3.2.3 on 2022-12-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20221214_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('id',), 'verbose_name': '员工表', 'verbose_name_plural': '员工表'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept_belong_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='update_datetime',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
