# Generated by Django 3.2.3 on 2022-12-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20221214_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
